"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('FEDECACAO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['allpayfedecacao.com']

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = ['https://allpayfedecacao.com']

CORS_ALLOW_CREDENTIALS = True


# Application definition

INSTALLED_APPS = [
    "seguridad.apps.SeguridadConfig",
    "recaudos.apps.RecaudosConfig",
    "reportes.apps.ReportesConfig",
    "gpt.apps.GptConfig",
    
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    'channels',
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    'storages',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'EXCEPTION_HANDLER': 'seguridad.custom_exception_handler.api_exception_handler'
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id_usuario',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=30),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'build'),
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#ASGI_APPLICATION = 'backend.asgi.application'

WSGI_APPLICATION = "backend.wsgi.application"

TIME_ZONE = 'America/Bogota'
USE_TZ = True

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('FEDECACAO_DB_NAME'),
        'USER': os.environ.get('FEDECACAO_DB_USER'),
        'PASSWORD': os.environ.get('FEDECACAO_DB_PASSWORD'),
        'HOST': os.environ.get('FEDECACAO_DB_HOST'),
        'PORT': os.environ.get('FEDECACAO_DB_PORT'),
        'ATOMIC_REQUESTS': True
    }
}



AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME")



AWS_S3_ADDRESSING_STYLE = "virtual"
AWS_S3_FILE_OVERWRITE = False  # No sobrescribir archivos
AWS_QUERYSTRING_AUTH = False  # Deshabilita autenticación en URL (opcional) 
AWS_S3_SIGNATURE_VERSION = "s3v4"  # Versión de la firma

# Configurar Django-Storages para usar S3
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

STORAGES ={
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

#Configuracion de Redis
REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 0


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'origin',
    'user-agent',
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "es-co" 

TIME_ZONE = "America/Bogota"  

USE_I18N = True

USE_TZ = True 


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
# con python manage.py collectstatic centralizamos todos los arhivos 
STATIC_ROOT = "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


FRONTEND_URL = os.environ.get('FRONTEND_URL')

AUTHENTICATION_360_NRS = os.environ.get('AUTHENTICATION_360_NRS')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get('FEDECACAO_EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('FEDECACAO_EMAIL_HOST_PASSWORD')


# OPENPAY
OPENPAY_MERCHANT_ID = os.environ.get('OPENPAY_MERCHANT_ID')
OPENPAY_PRIVATE_API_KEY = os.environ.get('OPENPAY_PRIVATE_API_KEY')
OPENPAY_BASE_URL = os.environ.get('OPENPAY_BASE_URL')

# ZONAPAGOS
ZPAGOS = {
    "BASE": os.getenv("ZPAGOS_API_BASE", "https://www.zonapagos.com/Apis_CicloPago/api"),
    "ID_COMERCIO": int(os.getenv("ZPAGOS_ID_COMERCIO", "0")),
    "USUARIO": os.getenv("ZPAGOS_USUARIO", ""),
    "CLAVE": os.getenv("ZPAGOS_CLAVE", ""),
    "CALLBACK_BASE": os.getenv("ZPAGOS_CALLBACK_BASE", ""),
    "T_RUTA": os.getenv("ZPAGOS_T_RUTA", ""),
    "CODIGO_SERVICIO": os.getenv("ZPAGOS_CODIGO_SERVICIO", ""),
    "NIT": os.getenv("ZPAGOS_NIT", ""),
    "IPS_PERMITIDAS": [ip.strip() for ip in os.getenv("ZPAGOS_IPS_PERMITIDAS","127.0.0.1/32").split(",") if ip.strip()],
}


AUTH_USER_MODEL = 'seguridad.User'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5 MB en bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5 MB en bytes




# """
# Django settings for backend project.

# Generated by 'django-admin startproject' using Django 4.1.7.

# For more information on this file, see
# https://docs.djangoproject.com/en/4.1/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/4.1/ref/settings/
# """

# from datetime import timedelta
# import os
# from pathlib import Path
# from dotenv import load_dotenv
# load_dotenv()
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.environ.get('FEDECACAO_SECRET_KEY')

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = [
#     'recaudosfondonacionaldelcacao.com', 
#     'www.recaudosfondonacionaldelcacao.com',
#     'localhost',
#     '127.0.0.1',
#     '10.0.101.100',  # ← AGREGAR ESTA IP
#     '10.0.0.0/16',
# ]

# ALLOWED_HOSTS += ['*']

# CSRF_TRUSTED_ORIGINS = [
#     "https://recaudosfondonacionaldelcacao.com", 
#     "https://www.recaudosfondonacionaldelcacao.com"
# ]

# CORS_ALLOW_CREDENTIALS = True
# USE_X_FORWARDED_HOST = True
# SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# # CORS CONFIGURATION: Orígenes permitidos (Debe incluir la URL exacta de tu frontend)
# CORS_ALLOWED_ORIGINS = [
#     "https://recaudosfondonacionaldelcacao.com", 
#     "https://www.recaudosfondonacionaldelcacao.com", # <--- URL de tu frontend
#     "http://localhost:3000",
#     "http://localhost:5173"
# ]

# CORS_ALLOWED_ORIGIN_REGEXES = [
#     r"^https://\w+\.recaudosfondonacionaldelcacao\.com$",
# ]

# # Application definition

# INSTALLED_APPS = [
#     "corsheaders", # <--- DEBE ESTAR AQUÍ

#     "seguridad.apps.SeguridadConfig",
#     "recaudos.apps.RecaudosConfig",
#     "reportes.apps.ReportesConfig",
#     "gpt.apps.GptConfig",

#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",

#     'channels',     
#     "rest_framework",
#     "rest_framework_simplejwt",
#     'storages',
# ]

# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ),
#     'EXCEPTION_HANDLER': 'seguridad.custom_exception_handler.api_exception_handler'
# }

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(days=2),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
#     'ROTATE_REFRESH_TOKENS': False,
#     'BLACKLIST_AFTER_ROTATION': True,
#     'UPDATE_LAST_LOGIN': False,

#     'ALGORITHM': 'HS256',
#     'VERIFYING_KEY': None,
#     'AUDIENCE': None,
#     'ISSUER': None,

#     'AUTH_HEADER_TYPES': ('Bearer',),
#     'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
#     'USER_ID_FIELD': 'id_usuario',
#     'USER_ID_CLAIM': 'user_id',

#     'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
#     'TOKEN_TYPE_CLAIM': 'token_type',

#     'JTI_CLAIM': 'jti',

#     'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
#     'SLIDING_TOKEN_LIFETIME': timedelta(minutes=30),
#     'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
# }

# MIDDLEWARE = [
#     'corsheaders.middleware.CorsMiddleware', # <--- DEBE ESTAR AL INICIO
#     "django.middleware.security.SecurityMiddleware",
#     'whitenoise.middleware.WhiteNoiseMiddleware',
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware", # Puede causar conflicto con OPTIONS
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",

# ]

# ROOT_URLCONF = "backend.urls"

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [
#             os.path.join(BASE_DIR, 'build'),
#             os.path.join(BASE_DIR, 'templates')
#         ],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# #ASGI_APPLICATION = 'backend.asgi.application'

# WSGI_APPLICATION = "backend.wsgi.application"

# TIME_ZONE = 'America/Bogota'
# USE_TZ = True

# # Database
# # https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.environ.get('FEDECACAO_DB_NAME'),
#         'USER': os.environ.get('FEDECACAO_DB_USER'),
#         'PASSWORD': os.environ.get('FEDECACAO_DB_PASSWORD'),
#         'HOST': os.environ.get('FEDECACAO_DB_HOST'),
#         'PORT': os.environ.get('FEDECACAO_DB_PORT'),
#         'ATOMIC_REQUESTS': True
#     }
# }



# AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
# AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
# AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
# AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME")



# AWS_S3_ADDRESSING_STYLE = "virtual"
# AWS_S3_FILE_OVERWRITE = False  # No sobrescribir archivos
# AWS_QUERYSTRING_AUTH = False  # Deshabilita autenticación en URL (opcional) 
# AWS_S3_SIGNATURE_VERSION = "s3v4"  # Versión de la firma

# # Configurar Django-Storages para usar S3
# # DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

# STORAGES = {
#     "default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
#     "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
# }

# #Configuracion de Redis
# REDIS_HOST = 'localhost'
# REDIS_PORT = 6379
# REDIS_DB = 0


# # Password validation
# # https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
#     },
#     {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
#     {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
#     {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
# ]

# # CORS_ORIGIN_ALLOW_ALL = True

# CORS_ALLOW_METHODS = [
#     'DELETE',
#     'GET',
#     'OPTIONS',
#     'PATCH',
#     'POST',
#     'PUT',
# ]

# # Modificación CRÍTICA: Eliminando headers CORS redundantes
# CORS_ALLOW_HEADERS = [
#     'accept',
#     'accept-encoding',
#     'authorization',
#     'content-type',
#     'dnt',
#     'origin',
#     'user-agent',
#     'x-csrftoken',
#     'x-requested-with',
#     # 'access-control-allow-origin',          <--- ELIMINADO
#     # 'access-control-allow-credentials',     <--- ELIMINADO
# ]

# # NUEVO: Exponer headers personalizados si los necesitas
# CORS_EXPOSE_HEADERS = [
#     'content-type',
#     'authorization',
#     'X-CSRFToken'
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/4.1/topics/i18n/

# LANGUAGE_CODE = "es-co" 

# TIME_ZONE = "America/Bogota"  

# USE_I18N = True

# USE_TZ = True 


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/4.1/howto/static-files/

# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.1/howto/static-files/

# STATIC_URL = "static/"
# # con python manage.py collectstatic centralizamos todos los arhivos 
# STATIC_ROOT = BASE_DIR / "staticfiles"
# STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"


# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'


# FRONTEND_URL = os.environ.get('FRONTEND_URL')

# AUTHENTICATION_360_NRS = os.environ.get('AUTHENTICATION_360_NRS')

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_USE_TLS = True
# EMAIL_HOST = 'smtp.office365.com'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = os.environ.get('FEDECACAO_EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = os.environ.get('FEDECACAO_EMAIL_HOST_PASSWORD')


# # OPENPAY
# OPENPAY_MERCHANT_ID = os.environ.get('OPENPAY_MERCHANT_ID')
# OPENPAY_PRIVATE_API_KEY = os.environ.get('OPENPAY_PRIVATE_API_KEY')
# OPENPAY_BASE_URL = os.environ.get('OPENPAY_BASE_URL')

# # ZONAPAGOS
# ZPAGOS = {
#     "BASE": os.getenv("ZPAGOS_API_BASE", "https://www.zonapagos.com/Apis_CicloPago/api"),
#     "ID_COMERCIO": int(os.getenv("ZPAGOS_ID_COMERCIO", "0")),
#     "USUARIO": os.getenv("ZPAGOS_USUARIO", ""),
#     "CLAVE": os.getenv("ZPAGOS_CLAVE", ""),
#     "CALLBACK_BASE": os.getenv("ZPAGOS_CALLBACK_BASE", ""),
#     "T_RUTA": os.getenv("ZPAGOS_T_RUTA", ""),
#     "CODIGO_SERVICIO": os.getenv("ZPAGOS_CODIGO_SERVICIO", ""),
#     "NIT": os.getenv("ZPAGOS_NIT", ""),
#     "IPS_PERMITIDAS": [ip.strip() for ip in os.getenv("ZPAGOS_IPS_PERMITIDAS","127.0.0.1/32").split(",") if ip.strip()],
# }


# AUTH_USER_MODEL = 'seguridad.User'

# # Default primary key field type
# # https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5 MB en bytes
# FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5 MB en bytes

# SESSION_COOKIE_SAMESITE = 'None'
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SAMESITE = 'None'
# CSRF_COOKIE_SECURE = True

# # Si usas JWT y no sesiones/cookies, es buena práctica desactivar el nombre de la cookie.
# # La línea siguiente define la variable que causó el error:
# CSRF_COOKIE_NAME = None 

# # Este bloque elimina el middleware CSRF si no se va a usar la cookie.
# # (Esto es común en APIs REST basadas en Token como JWT)
# if not CSRF_COOKIE_NAME and 'django.middleware.csrf.CsrfViewMiddleware' in MIDDLEWARE:
#     MIDDLEWARE.remove('django.middleware.csrf.CsrfViewMiddleware')


# if not DEBUG:
#     SECURE_HSTS_SECONDS = 31536000  # 1 año
#     SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#     SECURE_HSTS_PRELOAD = True
#     SECURE_SSL_REDIRECT = True
#     SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# # """
# # Django settings for backend project.

# # Generated by 'django-admin startproject' using Django 4.1.7.

# # For more information on this file, see
# # https://docs.djangoproject.com/en/4.1/topics/settings/

# # For the full list of settings and their values, see
# # https://docs.djangoproject.com/en/4.1/ref/settings/
# # """

# # from datetime import timedelta
# # import os
# # from pathlib import Path
# # from dotenv import load_dotenv
# # load_dotenv()
# # # Build paths inside the project like this: BASE_DIR / 'subdir'.
# # BASE_DIR = Path(__file__).resolve().parent.parent


# # # Quick-start development settings - unsuitable for production
# # # See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# # # SECURITY WARNING: keep the secret key used in production secret!
# # SECRET_KEY = os.environ.get('FEDECACAO_SECRET_KEY')

# # # SECURITY WARNING: don't run with debug turned on in production!
# # DEBUG = True

# # ALLOWED_HOSTS = [
# #     'recaudosfondonacionaldelcacao.com', 
# #     'www.recaudosfondonacionaldelcacao.com',
# #     'localhost',
# #     '127.0.0.1',
# #     '10.0.101.100',  # ← AGREGAR ESTA IP
# #     '10.0.0.0/16',
# # ]

# # ALLOWED_HOSTS += ['*']

# # CSRF_TRUSTED_ORIGINS = [
# #     "https://recaudosfondonacionaldelcacao.com", 
# #     "https://www.recaudosfondonacionaldelcacao.com"
# # ]

# # CORS_ALLOW_CREDENTIALS = True
# # USE_X_FORWARDED_HOST = True
# # SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# # CORS_ALLOWED_ORIGINS = [
# #     "https://recaudosfondonacionaldelcacao.com", 
# #     "https://www.recaudosfondonacionaldelcacao.com",
# #     "http://localhost:3000",
# #     "http://localhost:5173"
# # ]

# # CORS_ALLOWED_ORIGIN_REGEXES = [
# #     r"^https://\w+\.recaudosfondonacionaldelcacao\.com$",
# # ]

# # # Application definition

# # INSTALLED_APPS = [
# #     "corsheaders",
    
# #     "seguridad.apps.SeguridadConfig",
# #     "recaudos.apps.RecaudosConfig",
# #     "reportes.apps.ReportesConfig",
# #     "gpt.apps.GptConfig",
    
# #     "django.contrib.admin",
# #     "django.contrib.auth",
# #     "django.contrib.contenttypes",
# #     "django.contrib.sessions",
# #     "django.contrib.messages",
# #     "django.contrib.staticfiles",
    
# #     'channels',    
# #     "rest_framework",
# #     "rest_framework_simplejwt",
# #     'storages',
# # ]

# # REST_FRAMEWORK = {
# #     'DEFAULT_AUTHENTICATION_CLASSES': (
# #         'rest_framework_simplejwt.authentication.JWTAuthentication',
# #     ),
# #     'EXCEPTION_HANDLER': 'seguridad.custom_exception_handler.api_exception_handler'
# # }

# # SIMPLE_JWT = {
# #     'ACCESS_TOKEN_LIFETIME': timedelta(days=2),
# #     'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
# #     'ROTATE_REFRESH_TOKENS': False,
# #     'BLACKLIST_AFTER_ROTATION': True,
# #     'UPDATE_LAST_LOGIN': False,

# #     'ALGORITHM': 'HS256',
# #     'VERIFYING_KEY': None,
# #     'AUDIENCE': None,
# #     'ISSUER': None,

# #     'AUTH_HEADER_TYPES': ('Bearer',),
# #     'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
# #     'USER_ID_FIELD': 'id_usuario',
# #     'USER_ID_CLAIM': 'user_id',

# #     'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
# #     'TOKEN_TYPE_CLAIM': 'token_type',

# #     'JTI_CLAIM': 'jti',

# #     'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
# #     'SLIDING_TOKEN_LIFETIME': timedelta(minutes=30),
# #     'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
# # }

# # MIDDLEWARE = [
# #     'corsheaders.middleware.CorsMiddleware',
# #     "django.middleware.security.SecurityMiddleware",
# #     'whitenoise.middleware.WhiteNoiseMiddleware',
# #     "django.contrib.sessions.middleware.SessionMiddleware",
# #     "django.middleware.common.CommonMiddleware",
# #     "django.middleware.csrf.CsrfViewMiddleware",
# #     "django.contrib.auth.middleware.AuthenticationMiddleware",
# #     "django.contrib.messages.middleware.MessageMiddleware",
# #     "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
# # ]

# # ROOT_URLCONF = "backend.urls"

# # TEMPLATES = [
# #     {
# #         'BACKEND': 'django.template.backends.django.DjangoTemplates',
# #         'DIRS': [
# #             os.path.join(BASE_DIR, 'build'),
# #             os.path.join(BASE_DIR, 'templates')
# #         ],
# #         'APP_DIRS': True,
# #         'OPTIONS': {
# #             'context_processors': [
# #                 'django.template.context_processors.debug',
# #                 'django.template.context_processors.request',
# #                 'django.contrib.auth.context_processors.auth',
# #                 'django.contrib.messages.context_processors.messages',
# #             ],
# #         },
# #     },
# # ]

# # #ASGI_APPLICATION = 'backend.asgi.application'

# # WSGI_APPLICATION = "backend.wsgi.application"

# # TIME_ZONE = 'America/Bogota'
# # USE_TZ = True

# # # Database
# # # https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql',
# #         'NAME': os.environ.get('FEDECACAO_DB_NAME'),
# #         'USER': os.environ.get('FEDECACAO_DB_USER'),
# #         'PASSWORD': os.environ.get('FEDECACAO_DB_PASSWORD'),
# #         'HOST': os.environ.get('FEDECACAO_DB_HOST'),
# #         'PORT': os.environ.get('FEDECACAO_DB_PORT'),
# #         'ATOMIC_REQUESTS': True
# #     }
# # }



# # AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
# # AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
# # AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
# # AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME")



# # AWS_S3_ADDRESSING_STYLE = "virtual"
# # AWS_S3_FILE_OVERWRITE = False  # No sobrescribir archivos
# # AWS_QUERYSTRING_AUTH = False  # Deshabilita autenticación en URL (opcional) 
# # AWS_S3_SIGNATURE_VERSION = "s3v4"  # Versión de la firma

# # # Configurar Django-Storages para usar S3
# # # DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

# # STORAGES = {
# #     "default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
# #     "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
# # }

# # #Configuracion de Redis
# # REDIS_HOST = 'localhost'
# # REDIS_PORT = 6379
# # REDIS_DB = 0


# # # Password validation
# # # https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

# # AUTH_PASSWORD_VALIDATORS = [
# #     {
# #         "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
# #     },
# #     {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
# #     {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
# #     {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
# # ]

# # # CORS_ORIGIN_ALLOW_ALL = True

# # CORS_ALLOW_METHODS = [
# #     'DELETE',
# #     'GET',
# #     'OPTIONS',
# #     'PATCH',
# #     'POST',
# #     'PUT',
# # ]

# # CORS_ALLOW_HEADERS = [
# #     'accept',
# #     'accept-encoding',
# #     'authorization',
# #     'content-type',
# #     'dnt',
# #     'origin',
# #     'user-agent',
# #     'x-csrftoken',
# #     'x-requested-with',
# #     'access-control-allow-origin',
# #     'access-control-allow-credentials',
# # ]

# # # ✅ NUEVO: Exponer headers personalizados si los necesitas
# # CORS_EXPOSE_HEADERS = [
# #     'content-type',
# #     'authorization',
# #     'X-CSRFToken'
# # ]


# # # Internationalization
# # # https://docs.djangoproject.com/en/4.1/topics/i18n/

# # LANGUAGE_CODE = "es-co" 

# # TIME_ZONE = "America/Bogota"  

# # USE_I18N = True

# # USE_TZ = True 


# # # Static files (CSS, JavaScript, Images)
# # # https://docs.djangoproject.com/en/4.1/howto/static-files/

# # # Static files (CSS, JavaScript, Images)
# # # https://docs.djangoproject.com/en/5.1/howto/static-files/

# # STATIC_URL = "static/"
# # # con python manage.py collectstatic centralizamos todos los arhivos 
# # STATIC_ROOT = BASE_DIR / "staticfiles"
# # STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
# # STATICFILES_DIRS = [BASE_DIR / "static"]

# # MEDIA_URL = '/media/'
# # MEDIA_ROOT = BASE_DIR / 'media'


# # FRONTEND_URL = os.environ.get('FRONTEND_URL')

# # AUTHENTICATION_360_NRS = os.environ.get('AUTHENTICATION_360_NRS')

# # EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# # EMAIL_USE_TLS = True
# # EMAIL_HOST = 'smtp.gmail.com'
# # EMAIL_PORT = 587
# # EMAIL_HOST_USER = os.environ.get('FEDECACAO_EMAIL_HOST_USER')
# # EMAIL_HOST_PASSWORD = os.environ.get('FEDECACAO_EMAIL_HOST_PASSWORD')


# # # OPENPAY
# # OPENPAY_MERCHANT_ID = os.environ.get('OPENPAY_MERCHANT_ID')
# # OPENPAY_PRIVATE_API_KEY = os.environ.get('OPENPAY_PRIVATE_API_KEY')
# # OPENPAY_BASE_URL = os.environ.get('OPENPAY_BASE_URL')

# # # ZONAPAGOS
# # ZPAGOS = {
# #     "BASE": os.getenv("ZPAGOS_API_BASE", "https://www.zonapagos.com/Apis_CicloPago/api"),
# #     "ID_COMERCIO": int(os.getenv("ZPAGOS_ID_COMERCIO", "0")),
# #     "USUARIO": os.getenv("ZPAGOS_USUARIO", ""),
# #     "CLAVE": os.getenv("ZPAGOS_CLAVE", ""),
# #     "CALLBACK_BASE": os.getenv("ZPAGOS_CALLBACK_BASE", ""),
# #     "T_RUTA": os.getenv("ZPAGOS_T_RUTA", ""),
# #     "CODIGO_SERVICIO": os.getenv("ZPAGOS_CODIGO_SERVICIO", ""),
# #     "NIT": os.getenv("ZPAGOS_NIT", ""),
# #     "IPS_PERMITIDAS": [ip.strip() for ip in os.getenv("ZPAGOS_IPS_PERMITIDAS","127.0.0.1/32").split(",") if ip.strip()],
# # }


# # AUTH_USER_MODEL = 'seguridad.User'

# # # Default primary key field type
# # # https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

# # DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# # DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5 MB en bytes
# # FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5 MB en bytes

# # SESSION_COOKIE_SAMESITE = 'None'
# # SESSION_COOKIE_SECURE = True
# # CSRF_COOKIE_SAMESITE = 'None'
# # CSRF_COOKIE_SECURE = True

# # if not DEBUG:
# #     SECURE_HSTS_SECONDS = 31536000  # 1 año
# #     SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# #     SECURE_HSTS_PRELOAD = True
# #     SECURE_SSL_REDIRECT = True
# #     SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
