export interface RepresentanteLegalData {
    id_persona: number;
    representante_legal_data: any;
    tiene_usuario: boolean;
    primer_nombre: string;
    segundo_nombre: string;
    primer_apellido: string;
    segundo_apellido: string;
    cod_departamento_expedicion: string;
    cod_departamento_residencia: string;
    cod_departamento_notificacion: string;
    cod_departamento_laboral: string;
    archivo_rut: string | null;
    camaraComercio: string | null;
    documentoRepresentante: string | null;
    nombre_pais: string;
    nombre_departamento_residencia: string;
    nombre_municipio_residencia: string;
    nombre_departamento_notificacion: string;
    nombre_municipio_notificacion: string;
    nombre_departamento_laboral: string;
    nombre_municipio_laboral: string;
    nombre_municipio_expedicion: string;
    nombre_naturaleza_empresa: string | null;
    numero_documento: string;
    proveedor: boolean;
    digito_verificacion: string | null;
    tipo_persona: string;
    cod_naturaleza_empresa: string | null;
    razon_social: string | null;
    nombre_comercial: string;
    direccion_residencia: string;
    direccion_laboral: string;
    direccion_notificaciones: string;
    direccion_notificacion_referencia: string;
    email: string;
    email_empresarial: string;
    telefono_fijo_residencial: string;
    telefono_celular: string;
    telefono_empresa: string | null;
    telefono_celular_empresa: string | null;
    telefono_empresa_2: string;
    fecha_cambio_representante_legal: string | null;
    fecha_inicio_cargo_rep_legal: string | null;
    fecha_nacimiento: string;
    fecha_inicio_cargo_actual: string | null;
    fecha_a_finalizar_cargo_actual: string | null;
    acepta_notificacion_sms: boolean;
    acepta_notificacion_email: boolean;
    fecha_ultim_actualizacion_autorizaciones: string | null;
    acepta_tratamiento_datos: boolean;
    fecha_creacion: string;
    fecha_ultim_actualiz_diferente_crea: string | null;
    coordenada_x: number | null;
    coordenada_y: number | null;
    tipo_documento: string;
    cod_municipio_expedicion_id: string;
    municipio_residencia: string;
    cod_municipio_laboral_nal: string;
    cod_municipio_notificacion_nal: string;
    cod_pais_nacionalidad_empresa: string | null;
    representante_legal: number | null;
    pais_nacimiento: string;
    sexo: string;
    id_cargo: number | null;
    id_persona_crea: number;
    id_persona_ultim_actualiz_diferente_crea: number | null;
}

export interface PersonaData {
    id_persona: number;
    representante_legal_data: RepresentanteLegalData | null;
    tiene_usuario: boolean;
    primer_nombre: string;
    segundo_nombre: string;
    primer_apellido: string;
    segundo_apellido: string;
    cod_departamento_expedicion: string;
    cod_departamento_residencia: string;
    cod_departamento_notificacion: string;
    cod_departamento_laboral: string;
    archivo_rut: string | null;
    camaraComercio: string | null;
    documentoRepresentante: string | null;
    nombre_pais: string;
    nombre_departamento_residencia: string;
    nombre_municipio_residencia: string;
    nombre_departamento_notificacion: string;
    nombre_municipio_notificacion: string;
    nombre_departamento_laboral: string;
    nombre_municipio_laboral: string;
    nombre_municipio_expedicion: string;
    nombre_naturaleza_empresa: string | null;
    numero_documento: string;
    proveedor: boolean;
    digito_verificacion: string | null;
    tipo_persona: string;
    cod_naturaleza_empresa: string | null;
    razon_social: string | null;
    nombre_comercial: string;
    direccion_residencia: string | null;
    direccion_laboral: string | null;
    direccion_notificaciones: string;
    direccion_notificacion_referencia: string | null;
    email: string;
    email_empresarial: string | null;
    telefono_fijo_residencial: string | null;
    telefono_celular: string;
    telefono_empresa: string | null;
    telefono_celular_empresa: string | null;
    telefono_empresa_2: string;
    fecha_cambio_representante_legal: string | null;
    fecha_inicio_cargo_rep_legal: string | null;
    fecha_nacimiento: string | null;
    fecha_inicio_cargo_actual: string | null;
    fecha_a_finalizar_cargo_actual: string | null;
    acepta_notificacion_sms: boolean;
    acepta_notificacion_email: boolean;
    fecha_ultim_actualizacion_autorizaciones: string | null;
    acepta_tratamiento_datos: boolean | null;
    fecha_creacion: string;
    fecha_ultim_actualiz_diferente_crea: string | null;
    coordenada_x: number | null;
    coordenada_y: number | null;
    tipo_documento: string;
    cod_municipio_expedicion_id: string;
    municipio_residencia: string;
    cod_municipio_laboral_nal: string;
    cod_municipio_notificacion_nal: string;
    cod_pais_nacionalidad_empresa: string | null;
    representante_legal: number | null;
    pais_nacimiento: string | null;
    sexo: string;
    cod_tipo_comprador: string;
    id_cargo: number | null;
    id_persona_crea: number;
    id_persona_ultim_actualiz_diferente_crea: number | null;
}

export interface UserProfileData {
    id_usuario: number;
    _id: number;
    isAdmin: boolean;
    id_usuario_creador: number | null;
    persona: PersonaData;
    image_profile: string;
    nombre_de_usuario: string;
    password: string;
    is_active: boolean;
    is_superuser: boolean;
    is_staff: boolean;
    is_blocked: boolean;
    creado_por_portal: boolean;
    created_at: string;
    activated_at: string | null;
    tipo_usuario: string;
    tiene_2FA: boolean;
    last_login: string | null;
    groups: any[];
    user_permissions: any[];
    persona_2fa: any[];
}

export interface UserProfileResponse {
    success: boolean;
    data: UserProfileData;
    message?: string;
} 